# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.9.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.9.5/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danny/Dev/Sources/xlexview

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danny/Dev/Sources/xlexview

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.9.5/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.9.5/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danny/Dev/Sources/xlexview/CMakeFiles /Users/danny/Dev/Sources/xlexview/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danny/Dev/Sources/xlexview/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named xlexview

# Build rule for target.
xlexview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xlexview
.PHONY : xlexview

# fast build rule for target.
xlexview/fast:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/build
.PHONY : xlexview/fast

src/font.o: src/font.c.o

.PHONY : src/font.o

# target to build an object file
src/font.c.o:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/font.c.o
.PHONY : src/font.c.o

src/font.i: src/font.c.i

.PHONY : src/font.i

# target to preprocess a source file
src/font.c.i:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/font.c.i
.PHONY : src/font.c.i

src/font.s: src/font.c.s

.PHONY : src/font.s

# target to generate assembly for a file
src/font.c.s:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/font.c.s
.PHONY : src/font.c.s

src/list.o: src/list.c.o

.PHONY : src/list.o

# target to build an object file
src/list.c.o:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/list.c.o
.PHONY : src/list.c.o

src/list.i: src/list.c.i

.PHONY : src/list.i

# target to preprocess a source file
src/list.c.i:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/list.c.i
.PHONY : src/list.c.i

src/list.s: src/list.c.s

.PHONY : src/list.s

# target to generate assembly for a file
src/list.c.s:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/list.c.s
.PHONY : src/list.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/main.c.s
.PHONY : src/main.c.s

src/parse.o: src/parse.c.o

.PHONY : src/parse.o

# target to build an object file
src/parse.c.o:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/parse.c.o
.PHONY : src/parse.c.o

src/parse.i: src/parse.c.i

.PHONY : src/parse.i

# target to preprocess a source file
src/parse.c.i:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/parse.c.i
.PHONY : src/parse.c.i

src/parse.s: src/parse.c.s

.PHONY : src/parse.s

# target to generate assembly for a file
src/parse.c.s:
	$(MAKE) -f CMakeFiles/xlexview.dir/build.make CMakeFiles/xlexview.dir/src/parse.c.s
.PHONY : src/parse.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... xlexview"
	@echo "... src/font.o"
	@echo "... src/font.i"
	@echo "... src/font.s"
	@echo "... src/list.o"
	@echo "... src/list.i"
	@echo "... src/list.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parse.o"
	@echo "... src/parse.i"
	@echo "... src/parse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

